name: runtime_image

on:
  push:
    branches: [ main ]
    paths:
      - 'runtime/Dockerfile'
      - '.github/workflows/on_merge_to_runtime_image.yml'

env:
  REGISTRY: ghcr.io
  OPENCV_VERSION: "4.5.5"
  BUILD_IMAGE: "build"
  RUNTIME_IMAGE: "runtime"
  IMAGE_NAME: ${{ github.repository }}

jobs:

  merge:
    environment: ghcr.io
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Docker buildx
        uses: docker/setup-buildx-action@79abd3f86f79a9d68a23c75a09a9a85889262adf
        with:
          driver-opts: network=host

      - name: Install cosign
        if: github.event_name != 'pull_request'
        uses: sigstore/cosign-installer@d6a3abf1bdea83574e28d40543793018b6035605
        with:
          cosign-release: 'v1.7.1'

      - name: Log into registry ${{ env.REGISTRY }}
        if: github.event_name != 'pull_request'
        uses: docker/login-action@28218f9b04b4f3f62068d7b6ce6ca5b26e35336c
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GHCRIO_TOKEN }}

      - name: Pull build image
        run: docker pull ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ env.OPENCV_VERSION }}-${{ env.BUILD_IMAGE }}

      - name: Inspect build image
        id: build-image
        run: >-
          echo "::set-output name=digest::$(
            docker image inspect ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ env.OPENCV_VERSION }}-${{ env.BUILD_IMAGE }} | jq -r '.[] | .RepoDigests[]'
          )"

      - name: runtime image metadata
        id: runtime-meta
        uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ env.OPENCV_VERSION }}-${{ env.RUNTIME_IMAGE }}

      - name: "opencv-debian:<version>-runtime image building stage"
        id: runtime-image
        uses: docker/build-push-action@ac9327eae2b366085ac7f6a2d02df8aa8ead720a
        with:
          context: ./runtime
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ env.OPENCV_VERSION }}-${{ env.RUNTIME_IMAGE }}
          build-args: |
            BUILD_IMAGE_DIGEST_TAG=${{ steps.build-image.outputs.digest }}

      - name: Sign the published runtime image
        if: ${{ github.event_name != 'pull_request' }}
        env:
          COSIGN_EXPERIMENTAL: "true"
        run: cosign sign ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ env.OPENCV_VERSION }}-${{ env.RUNTIME_IMAGE }}@${{ steps.runtime-image.outputs.digest }}
