name: runtime_image

on:
  pull_request:
    branches: [ main ]
    paths:
      - 'runtime/Containerfile'

env:
  REGISTRY: ghcr.io
  OPENCV_VERSION: "4.5.5"
  BUILD_IMAGE: "build"
  RUNTIME_IMAGE: "runtime"
  IMAGE_NAME: ${{ github.repository }}

jobs:

  pr:
    environment: ghcr.io
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Docker buildx
        uses: docker/setup-buildx-action@79abd3f86f79a9d68a23c75a09a9a85889262adf
        with:
          driver-opts: network=host

      - name: Pull build image
        run: docker pull ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ env.OPENCV_VERSION }}-${{ env.BUILD_IMAGE }}

      - name: Inspect build image
        id: build-image
        run: >-
          echo "::set-output name=digest::$(
            docker image inspect ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ env.OPENCV_VERSION }}-${{ env.BUILD_IMAGE }} | jq -r '.[] | .RepoDigests[]'
          )"

      - name: "opencv-debian:<version>-runtime image building stage"
        id: runtime-image
        uses: docker/build-push-action@ac9327eae2b366085ac7f6a2d02df8aa8ead720a
        with:
          context: ./runtime
          push: false
          tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ env.OPENCV_VERSION }}-${{ env.RUNTIME_IMAGE }}
          build-args: |
            BUILD_IMAGE_DIGEST_TAG=${{ steps.build-image.outputs.digest }}
